name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.15.1

    - name: Install dependencies
      run: npm ci

    - name: Deploy to Production
      run: npx serverless deploy --stage prod
      env:
        AMAZON_ACCESS_KEY_ID: ${{ secrets.AMAZON_ACCESS_KEY_ID }}
        AMAZON_SECRET_ACCESS_KEY: ${{ secrets.AMAZON_SECRET_ACCESS_KEY }}
        AMAZON_CLOUD_FRONT_BASE_URL: ${{ secrets.AMAZON_CLOUD_FRONT_BASE_URL }}
        EXERCISE_BASE_URL: ${{ secrets.EXERCISE_BASE_URL }}
        EXERCISE_API_KEY: ${{ secrets.EXERCISE_API_KEY }}
        EXERCISE_CLOUD_FRONT_BASE_URL: ${{ secrets.EXERCISE_CLOUD_FRONT_BASE_URL }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}